### ISSUE TITLE
Icons disapear in Vertical Icon Only Mode 

### ISSUE THREAD

**Issue by 1darklyte** [nfm886/skin.cosmic#2]
Hello, 

Skin is nice and snappy on my Shield. When I changed the (Vertical View) Menu Style to Icon Only the icons disappear and the only icon showing for all sections is the Settings Icon.

I came from Auramod

*addition : So i swapped the view to "Icons + Text" and the text show up but the only icon under this view is also the Settings Icon. The rest are not showing on my install.

**Comment by Goldenfreddy0703** [comment]
Hey Sense you came from Auramod, This is not really a bug, Icons can sometimes be different if you switched from auramod to cosmic, its not really a bug, all you need to do is to go to Customize main menu & widgets and set those icons back again. This is probably due to the icons folder the developer used for this skin or skinshortcuts. Again, not really a bug, just need replacement.

I also tried what you said and have not seen it happen to my icons.

**Comment by Goldenfreddy0703** [comment]
Btw if you wanna see a real icon bug, Titan Bengie or Titan Bengie mod has you covered with that bug. The Titan skins are a mess when you add costume icons. 😂

**Comment by 1darklyte** [comment]
Manually re setting the icons worked and they show up now. 

Thanks
