### ISSUE TITLE
[Request] How to Trigger Seren after Clicking on Item

### ISSUE THREAD

**Issue by prazsky** [nfm886/skin.cosmic#44]
I followed the [video walkthrough](https://www.youtube.com/watch?v=0SstQgu8I9E) configuring + installing Cosmic and I couldn't find how to trigger Seren when I click on a movie/show in the lists.

Can provide logs or anything necessary. This is on a fresh install of Kodi 19

**Comment by nfm886** [comment]
Seren should be as a player in TMDbH. You can make sure if it's there by going to Settings > Add-ons > My Add-ons > Video add-ons > TheMovieDb Helper > Configure > Players... Play with these settings.

If there is no player for Seren add-on, then you must point widgets to Seren instead of TheMovieDbH.
Starting from there: https://youtu.be/0SstQgu8I9E?t=182 instead of going to Add-on > Video Add-on > TheMovieDb Helper, go to Add-on > Video add-on > Seren and use these entries as a widget.

Hope it helps. If not, please record a screen cast if possible what's the problem :)

**Comment by prazsky** [comment]
Closing as I resolved the problem.

TMDbH didn't detect (if it's supposed to) the Seren players so I added them by URL and it worked fine :)
